Added some useful features
Zavy86/WikiDocs pull request #126
Opened 2024-05-22 14:23 UTC by shaoziyang

Added some useful features, such as:

- page view count
- site visit count
- recent pages
- page and image files count
- random pages
- wallpaper
- image library
- page effects scripts

It is very easy to configure, DIY various styles.

2024-05-22 16:00 UTC, Zavy86 commented
oh wow! *_*

2024-05-22 20:08 UTC, vCoDMods commented
> oh wow! 🤩

Will you merge this to master?

2024-06-26 06:43 UTC, Zavy86 requested changes

2024-06-27 15:10 UTC, shaoziyang commented on common.php
> +function randint_day(){
generate daily random numbers for daily quotes

2024-06-27 16:11 UTC, shaoziyang commented on scripts/opacity_10.png
Used to set the transparency of the background image by overlaying the image.

2024-06-27 16:13 UTC, shaoziyang commented
Please ignore this pull request, I will submit a new one.

2024-06-27 16:13 UTC, closed without merging